### ISSUE TITLE
Pysbd just hangs🐛

### ISSUE THREAD

**Issue by kariato** [nipunsadvilkar/pySBD#76] opened 2020-08-24 19:13 UTC
**Describe the bug**
The process hangs .

**To Reproduce**
Input text - <f.302205302116302416302500302513915bd>
flat = "f.302205302116302416302500302513915bd"
print(flat)
x=segClean = pysbd.Segmenter(language="en", clean=True, char_span=False)
for z in x.segment(flat):
    print(z)

Example:
Input text - "My name is Jonas E. Smith. Please turn to p. 55."

**Expected behavior**
Return f.302205302116302416302500302513915

Example:
`['f.302205302116302416302500302513915bd']`

**Additional context**

**Comment by frankang** [comment] 2020-09-07 07:36
I'm unable to reproduce this error, tested on two machines.

**Comment by kariato** [comment] 2020-09-08 17:12
What version of python are you using I've been able to reproduce this at work and home. My machines are Red Hat and Mint using 
Python 3.7.4 (default, Nov 10 2011, 15:00:00) 
[GCC 9.3.0] on linux
![Screenshot from 2020-09-08 13-02-06](https://user-images.githubusercontent.com/1799644/92506496-8d587700-f1d3-11ea-9d02-2385471035db.png)

Sorry I had to let it run for 10 minutes to complete. If you make the numeric string longer the delay is even longer.  Try '''f.302205302116302163025003025139150030251391500302513915bd''' may be hours. It pegs one CPU core at 100%.

This is a problem. Unless waiting minutes to hours for a result is acceptable.

**Comment by nipunsadvilkar** [comment] 2020-09-11 08:48
I tried to recreate this error, unable to recreate it. Works for me on Mac OS (Darwin)

To dive into details, I would request you to provide the python traceback by hitting the interrupt key (normally Control-C or Delete) to raise `KeyboardInterrupt` exception during that hanging phase.

**Comment by kariato** [comment] 2020-09-11 19:13
/home/kariato/PycharmProjects/pySBD/venv/bin/python /home/kariato/PycharmProjects/pySBD/Teststub.py
Hello World. My name is Jonas. ['Hello World.', 'My name is Jonas.']
What is your name? My name is Jonas. ['What is your name?', 'My name is Jonas.']
There it is! I found it. ['There it is!', 'I found it.']
My name is Jonas E. Smith. ['My name is Jonas E. Smith.']
Please turn to p. 55. ['Please turn to p. 55.']
Were Jane and co. at the party? ['Were Jane and co. at the party?']
Traceback (most recent call last):
  File "/home/kariato/PycharmProjects/pySBD/Teststub.py", line 68, in <module>
    y=seg.segment(x[1])
  File "/home/kariato/PycharmProjects/pySBD/pysbd/segmenter.py", line 42, in segment
    segments = processor.process()
  File "/home/kariato/PycharmProjects/pySBD/pysbd/processor.py", line 47, in process
    self.replace_periods_before_numeric_references()
  File "/home/kariato/PycharmProjects/pySBD/pysbd/processor.py", line 159, in replace_periods_before_numeric_references
    r"∯\2\r\7", self.text)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
KeyboardInterrupt

Process finished with exit code 1

**Comment by kariato** [comment] 2020-09-11 19:14
Sorry new to this. Here is the stack dump

**Comment by kariato** [comment] 2020-09-13 14:50
I'll fork this repo and work on it. I've been mining a very large data set of data about 1TB so I'll try ro work on it abd get a pull request to you.

**Comment by nipunsadvilkar** [comment] 2020-09-16 14:20
@kariato Yes please do.

Few things you can do (since you are able to recreate the issue):

With the debugger locate at following location to check the value of `self.text`
`"/home/kariato/PycharmProjects/pySBD/pysbd/processor.py", line 159, in replace_periods_before_numeric_references
r"∯\2\r\7", self.text)`

then try to tweak the above regex with that `self.text` captured from above to get required substitution without hang

**Comment by nipunsadvilkar** [comment] 2020-10-08 11:42
Closing for now. Feel free to reopen with more details

**Closed by nipunsadvilkar** 2020-10-08 11:42 UTC
Labels: help wanted
